import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type DesktopLocale = 'en' | 'pt-BR';
export type DesktopLocalePreference = 'auto' | DesktopLocale;

const en = {
  'app.loading': 'Loading GorillaPunch…', 'app.quickUrl': 'Quick punch a URL…', 'app.quickUrlLabel': 'Quick punch URL', 'app.punch': 'Punch', 'app.dismiss': 'Dismiss notification', 'app.punchFailed': 'Punch failed.', 'app.reportNotFound': 'Report not found.', 'app.reportUnavailable': 'Report unavailable.', 'app.loadingReport': 'Loading report evidence…', 'app.reportDeleted': 'Report deleted.', 'app.reportSynced': 'Report synced to cloud.', 'app.watchAdded': 'Project watcher added.', 'app.pendingSynced': '{count} pending reports synced.', 'app.pendingSyncedSingular': '{count} pending report synced.',
  'app.localStatus': 'Local storage', 'app.signInStatus': 'Sign in to sync', 'app.profile': 'Profile and cloud settings', 'app.online': 'Online', 'app.offline': 'Offline',
  'window.minimize': 'Minimize', 'window.maximize': 'Maximize', 'window.restore': 'Restore', 'window.close': 'Close',
  'nav.label': 'Main navigation', 'nav.navigation': 'Navigation', 'nav.expand': 'Expand sidebar', 'nav.collapse': 'Collapse sidebar',
  'nav.overview': 'Overview', 'nav.history': 'Punch history', 'nav.monitor': 'Project monitor', 'nav.settings': 'Settings', 'nav.game': 'Gorilla Shot',
  'nav.cloud': 'Cloud sync', 'nav.local': 'Local storage', 'nav.localSaved': 'Saved on this PC', 'nav.signInSettings': 'Sign in in Settings', 'nav.quickPunch': 'Quick punch',
  'dashboard.checkEyebrow': 'LAUNCH READINESS CHECK', 'dashboard.title': 'Is your app ready to launch?', 'dashboard.subtitle': 'Check a development, staging, or public website before release.',
  'dashboard.urlLabel': 'Website URL', 'dashboard.urlPlaceholder': 'Enter a website address', 'dashboard.quick': 'Quick', 'dashboard.full': 'Full', 'dashboard.startPunch': 'Start punch', 'dashboard.starting': 'Starting…',
  'dashboard.reportsLocal': 'Reports saved on this PC', 'dashboard.signInSync': 'Sign in to sync reports', 'dashboard.syncPaused': 'Account sync is paused', 'dashboard.syncEnabled': 'Cloud sync enabled', 'dashboard.detected': 'Detected:',
  'dashboard.punches': 'Punches', 'dashboard.averageScore': 'Average score', 'dashboard.readyLaunch': 'Ready to launch', 'dashboard.syncedReports': 'Synced reports',
  'dashboard.activePunch': '{count} active punch', 'dashboard.activePunches': '{count} active punches', 'dashboard.cancel': 'Cancel', 'dashboard.latestEvidence': 'LATEST EVIDENCE', 'dashboard.recentPunches': 'Recent punches', 'dashboard.viewAll': 'View all',
  'history.eyebrow': 'REPORT LIBRARY', 'history.title': 'Punch history', 'history.subtitle': 'Reports saved on this PC stay here. Synced reports are available in your account.', 'history.search': 'Search by URL…', 'history.filter': 'Filter by status', 'history.allStatuses': 'All statuses', 'history.completed': 'Completed', 'history.running': 'Running', 'history.failed': 'Failed', 'history.cancelled': 'Cancelled', 'history.empty': 'No reports match these filters.',
  'scan.noPunches': 'No punches yet.', 'scan.startAddress': 'Start with a website address.', 'scan.savedAccount': 'Saved to your account', 'scan.savedLocal': 'Saved on this PC',
  'watch.eyebrow': 'AUTOMATION', 'watch.title': 'Project monitor', 'watch.subtitle': 'Choose a project folder and website address. GorillaPunch rechecks the site when you save code.', 'watch.createTitle': 'Monitor a project', 'watch.createSubtitle': 'Choose a website address and the project folder to watch.', 'watch.address': 'Website address', 'watch.auditType': 'Audit type', 'watch.quickAudit': 'Quick audit', 'watch.fullAudit': 'Full audit', 'watch.chooseFolder': 'Choose folder', 'watch.monitoring': 'Monitoring', 'watch.paused': 'Paused', 'watch.pause': 'Pause monitor', 'watch.resume': 'Resume monitor', 'watch.remove': 'Remove monitor', 'watch.lastStarted': 'last started {date}', 'watch.emptyTitle': 'No projects monitored', 'watch.emptySubtitle': 'Add a project to check its website after you save code.', 'watch.added': 'Project watcher added.',
  'settings.eyebrow': 'PREFERENCES', 'settings.title': 'Settings', 'settings.subtitle': 'Choose where reports go and adjust how audits run.', 'settings.storageTitle': 'Report storage', 'settings.storageSubtitle': 'Choose where new reports are saved.', 'settings.local': 'Local storage', 'settings.localDesc': 'Reports and screenshots stay on this PC. No account needed.', 'settings.ready': 'Ready to use', 'settings.cloud': 'Cloud sync', 'settings.cloudDesc': 'Sign in to sync completed report results to your account. Screenshots stay on this PC.', 'settings.unavailable': 'Unavailable right now', 'settings.connected': 'Account connected', 'settings.signInBelow': 'Sign in below', 'settings.avatarInvalid': 'Choose a PNG, JPEG, or WebP image under 8 MB.', 'settings.avatarProcessing': 'Image processing is unavailable.', 'settings.avatarCompression': 'This picture could not be compressed enough. Choose another image.',
  'settings.account': 'GorillaPunch account', 'settings.accountDesc': 'Sign in or create an account to sync reports.', 'settings.savingLocal': 'Saving reports locally', 'settings.pictureLabel': 'Choose profile picture', 'settings.saving': 'Saving…', 'settings.changePicture': 'Change picture', 'settings.remove': 'Remove', 'settings.pictureUpdated': 'Profile picture updated.', 'settings.pictureRemoved': 'Profile picture removed.', 'settings.pictureError': 'Could not update the profile picture.', 'settings.removePictureError': 'Could not remove picture.',
  'settings.syncing': 'Syncing…', 'settings.syncPending': 'Sync {count} pending', 'settings.signOut': 'Sign out', 'settings.signOutSuccess': 'Signed out.', 'settings.signOutError': 'Sign out failed. Please try again.', 'settings.createAccount': 'Create account', 'settings.signIn': 'Sign in', 'settings.accountSyncDesc': 'Use your GorillaPunch account to sync reports.', 'settings.name': 'Name', 'settings.email': 'Email', 'settings.password': 'Password', 'settings.passwordLong': 'Password (10 or more characters)', 'settings.acceptTerms': 'Accept the Terms and Privacy Policy to create an account.', 'settings.agreeTerms': 'I agree to the', 'settings.terms': 'Terms', 'settings.and': 'and', 'settings.privacy': 'Privacy Policy', 'settings.wait': 'Please wait…', 'settings.recovery': 'For account recovery, contact', 'settings.alreadyAccount': 'Already have an account? Sign in', 'settings.needAccount': 'Need an account? Create one', 'settings.emailConfirm': 'Check your email and confirm your account. Then sign in here to sync reports.', 'settings.accountReady': 'Account connected. Cloud sync is ready.', 'settings.connectError': 'We could not connect your account. Please try again.', 'settings.cloudUnavailable': 'Cloud sync unavailable', 'settings.cloudUnavailableDesc': 'Try again later or contact support. You can still save reports on this PC.', 'settings.language': 'Language', 'settings.english': 'English', 'settings.portuguese': 'Português (Brasil)',
  'settings.auditTitle': 'Audit options', 'settings.auditSubtitle': 'Choose how much of each site to check.', 'settings.defaultAudit': 'Default audit', 'settings.moreOptions': 'More options', 'settings.pages': 'Pages to check', 'settings.depth': 'Link depth', 'settings.timeLimit': 'Time limit (seconds)', 'settings.concurrency': 'Simultaneous audits', 'settings.recommended': '1 — recommended',
  'settings.preferencesTitle': 'App preferences', 'settings.preferencesSubtitle': 'Window and notification preferences.', 'settings.theme': 'Theme', 'settings.system': 'system', 'settings.dark': 'dark', 'settings.light': 'light', 'settings.minimizeTray': 'Minimize to tray on close', 'settings.notifications': 'Completion notifications', 'settings.findDevSites': 'Find development sites automatically', 'settings.launchStartup': 'Launch when Windows starts', 'settings.autoSync': 'Automatically sync completed reports', 'settings.checkUpdates': 'Check for updates', 'settings.checking': 'Checking…', 'settings.updatesUnavailable': 'The update service is unavailable right now.', 'settings.updateCurrent': 'GorillaPunch is up to date.', 'settings.updateAvailable': 'Version {version} is available.', 'settings.autoLanguage': 'System default',
  'report.back': 'Back', 'report.copyPrompt': 'Copy fix prompt', 'report.sync': 'Sync', 'report.punchMode': 'PUNCH', 'report.export': 'Export', 'report.delete': 'Delete report', 'report.launchGate': 'LAUNCH GATE', 'report.insufficient': 'INSUFFICIENT COVERAGE', 'report.noBlockers': 'No automated launch blockers were detected.', 'report.incomplete': 'Some essential checks could not complete. Review the evidence before deciding.', 'report.resolve': 'Resolve the highest severity evidence before launch.', 'report.blockers': 'blockers', 'report.critical': 'critical', 'report.high': 'high', 'report.coverage': 'coverage', 'report.savedAccount': 'Saved to your account', 'report.savedLocal': 'Saved on this PC', 'report.performance': 'Performance', 'report.security': 'Security', 'report.seo': 'SEO', 'report.accessibility': 'Accessibility', 'report.reliability': 'Reliability', 'report.ux': 'User experience', 'report.production': 'Production', 'report.findings': 'Findings', 'report.pages': 'Pages', 'report.screenshots': 'Screenshots', 'report.metrics': 'Metrics', 'report.search': 'Search evidence…', 'report.searchLabel': 'Search evidence', 'report.filterSeverity': 'Filter by severity', 'report.allSeverities': 'All severities', 'report.noneMatch': 'No findings match.', 'report.page': 'Page', 'report.status': 'Status', 'report.indexable': 'Indexable', 'report.loadTime': 'Load time', 'report.yes': 'Yes', 'report.no': 'No', 'report.captureAlt': 'Captured viewport {viewport}', 'report.imageUnavailable': 'Screenshot file unavailable', 'report.screenshotsLocal': 'Screenshots are saved only on the computer that ran the audit.', 'report.metric': 'Metric', 'report.value': 'Value', 'report.why': 'Why it matters', 'report.evidence': 'Evidence', 'report.reproduce': 'How to reproduce', 'report.recommendation': 'Recommendation', 'report.inspect': 'Inspect element live', 'report.closeDetails': 'Close finding details', 'report.savedFile': 'Saved to {path}', 'report.exportError': 'Export failed.', 'report.copiedPrompt': 'Fix prompt copied with {count} prioritized findings.', 'report.copiedPromptSingular': 'Fix prompt copied with {count} prioritized finding.', 'report.copiedSummary': 'Report summary copied.', 'report.copyError': 'Could not copy the fix prompt.', 'report.unavailable': 'Screenshot file unavailable', 'report.sevBlocker': 'Blocker', 'report.sevCritical': 'Critical', 'report.sevHigh': 'High', 'report.sevMedium': 'Medium', 'report.sevLow': 'Low', 'report.sevOpportunity': 'Opportunity', 'report.sevPassed': 'Passed',
  'arcade.eyebrow': 'DESKTOP ARCADE', 'arcade.title': 'Gorilla Shot', 'arcade.subtitle': 'Survive the arena, reboot its systems, and clear all three sectors.', 'arcade.loading': 'Loading the arena', 'arcade.loadingDescription': 'Loading game systems and rendering the sector…', 'arcade.volume': 'Game volume', 'arcade.gameLabel': 'Gorilla Shot game', 'arcade.sectorSurvival': 'Sector survival', 'arcade.savedLocal': 'Saved locally', 'arcade.offlinePending': 'Offline · sync pending', 'arcade.cloudSynced': 'Cloud progress synced', 'arcade.cloudPending': 'Cloud sync pending', 'arcade.mute': 'Mute audio', 'arcade.unmute': 'Unmute audio', 'arcade.pause': 'Pause game', 'arcade.resume': 'Resume game', 'arcade.fullscreen': 'Fullscreen', 'arcade.exitFullscreen': 'Exit fullscreen', 'arcade.fullscreenError': 'Fullscreen is unavailable in this window.', 'arcade.saveError': 'Game progress could not be saved.', 'arcade.startError': 'Could not start the game.', 'arcade.gameError': 'The game could not start.', 'arcade.cloudError': 'Cloud progress could not sync.', 'arcade.statsLabel': 'Current run statistics', 'arcade.sector': 'SECTOR', 'arcade.health': 'HEALTH', 'arcade.timeAlive': 'TIME ALIVE', 'arcade.score': 'SCORE', 'arcade.enemies': 'ENEMIES', 'arcade.systems': 'SYSTEMS', 'arcade.arena': 'Gorilla Shot arena', 'arcade.move': 'Move', 'arcade.aim': 'Aim', 'arcade.fire': 'Fire', 'arcade.deploy': 'Deploy sector', 'arcade.progressLabel': 'Gorilla Shot progress', 'arcade.progress': 'YOUR PROGRESS', 'arcade.record': 'Mission record', 'arcade.syncNow': 'Sync now', 'arcade.bestScore': 'BEST SCORE', 'arcade.longest': 'LONGEST SURVIVAL', 'arcade.totalTime': 'TOTAL TIME', 'arcade.runsClears': 'RUNS / CLEARS', 'arcade.recentRuns': 'Recent runs', 'arcade.runLabel': 'Sector {level}', 'arcade.points': 'pts', 'arcade.firstRecord': 'Finish a run to begin your mission record.', 'arcade.sectorOption': 'Sector {level}', 'arcade.cleared': 'CLEARED', 'arcade.failed': 'FAILED', 'arcade.abandoned': 'ABANDONED',
  'verdict.ready': 'READY TO LAUNCH', 'verdict.almost': 'ALMOST READY', 'verdict.notReady': 'NOT READY', 'verdict.doNotLaunch': 'DO NOT LAUNCH', 'verdict.insufficient': 'INSUFFICIENT COVERAGE',
  'stage.resolving': 'Resolving domain', 'stage.opening': 'Opening application', 'stage.headers': 'Reading response headers', 'stage.runtime': 'Inspecting browser runtime', 'stage.links': 'Walking internal links', 'stage.damage': 'Calculating the damage', 'stage.saving': 'Saving the Punch Report', 'stage.complete': 'Punch complete', 'stage.cancelled': 'Punch cancelled', 'stage.interrupted': 'This punch was interrupted', 'stage.closed': 'Desktop app closed before this punch completed', 'stage.queuePaused': 'Queue paused', 'stage.waitingBrowser': 'Waiting for a local browser', 'stage.warming': 'Warming up the gloves',
  'settings.errValidEmail': 'Enter a valid email address.', 'settings.errPassword': 'Enter your password.', 'settings.errPasswordTooLong': 'Use a password with 128 characters or fewer.', 'settings.errPasswordRange': 'Use a password between 10 and 128 characters.', 'settings.errCloudUnavailable': 'Cloud sync is unavailable right now. Try again later or contact support.', 'settings.errTooManyAttempts': 'Too many attempts. Wait a moment and try again.', 'settings.errReachAccount': 'We could not reach your account right now. Check your connection and try again.', 'settings.errBadCredentials': 'Email or password is incorrect. Please try again.', 'settings.errCouldNotSignIn': 'We could not sign in. Please try again.', 'settings.errAlreadyExists': 'An account with this email already exists. Sign in instead.', 'settings.errStrongerPassword': 'Choose a stronger password and try again.', 'settings.errCouldNotCreate': 'We could not create your account. Please try again.', 'settings.errConnectAccount': 'We could not connect your account. Please try again.',
  'misc.justNow': 'Just now', 'misc.complete': 'Complete', 'misc.queued': 'Queued', 'misc.cancelled': 'Cancelled', 'misc.failed': 'Failed', 'misc.somethingWrong': 'Something went wrong.',
} as const;

type MessageKey = keyof typeof en;
const pt: Record<MessageKey, string> = {
  'app.loading': 'Carregando o GorillaPunch…', 'app.quickUrl': 'Faça uma análise rápida de uma URL…', 'app.quickUrlLabel': 'URL para análise rápida', 'app.punch': 'Analisar', 'app.dismiss': 'Dispensar notificação', 'app.punchFailed': 'A análise falhou.', 'app.reportNotFound': 'Relatório não encontrado.', 'app.reportUnavailable': 'Relatório indisponível.', 'app.loadingReport': 'Carregando evidências do relatório…', 'app.reportDeleted': 'Relatório excluído.', 'app.reportSynced': 'Relatório sincronizado na nuvem.', 'app.watchAdded': 'Monitor de projeto adicionado.', 'app.pendingSynced': '{count} relatórios pendentes sincronizados.', 'app.pendingSyncedSingular': '{count} relatório pendente sincronizado.',
  'app.localStatus': 'Armazenamento local', 'app.signInStatus': 'Entre para sincronizar', 'app.profile': 'Perfil e configurações da nuvem', 'app.online': 'Conectado', 'app.offline': 'Desconectado',
  'window.minimize': 'Minimizar', 'window.maximize': 'Maximizar', 'window.restore': 'Restaurar', 'window.close': 'Fechar',
  'nav.label': 'Navegação principal', 'nav.navigation': 'Navegação', 'nav.expand': 'Expandir menu lateral', 'nav.collapse': 'Recolher menu lateral',
  'nav.overview': 'Visão geral', 'nav.history': 'Histórico de análises', 'nav.monitor': 'Monitor de projetos', 'nav.settings': 'Configurações', 'nav.game': 'Gorilla Shot',
  'nav.cloud': 'Sincronização na nuvem', 'nav.local': 'Armazenamento local', 'nav.localSaved': 'Salvo neste PC', 'nav.signInSettings': 'Entre em Configurações', 'nav.quickPunch': 'Análise rápida',
  'dashboard.checkEyebrow': 'VERIFICAÇÃO DE PRONTIDÃO PARA LANÇAMENTO', 'dashboard.title': 'Seu app está pronto para ser lançado?', 'dashboard.subtitle': 'Verifique um site de desenvolvimento, homologação ou produção antes do lançamento.',
  'dashboard.urlLabel': 'URL do site', 'dashboard.urlPlaceholder': 'Digite o endereço de um site', 'dashboard.quick': 'Rápida', 'dashboard.full': 'Completa', 'dashboard.startPunch': 'Iniciar análise', 'dashboard.starting': 'Iniciando…',
  'dashboard.reportsLocal': 'Relatórios salvos neste PC', 'dashboard.signInSync': 'Entre para sincronizar relatórios', 'dashboard.syncPaused': 'Sincronização da conta pausada', 'dashboard.syncEnabled': 'Sincronização na nuvem ativada', 'dashboard.detected': 'Detectados:',
  'dashboard.punches': 'Análises', 'dashboard.averageScore': 'Pontuação média', 'dashboard.readyLaunch': 'Prontos para lançamento', 'dashboard.syncedReports': 'Relatórios sincronizados',
  'dashboard.activePunch': '{count} análise ativa', 'dashboard.activePunches': '{count} análises ativas', 'dashboard.cancel': 'Cancelar', 'dashboard.latestEvidence': 'EVIDÊNCIAS RECENTES', 'dashboard.recentPunches': 'Análises recentes', 'dashboard.viewAll': 'Ver tudo',
  'history.eyebrow': 'BIBLIOTECA DE RELATÓRIOS', 'history.title': 'Histórico de análises', 'history.subtitle': 'Os relatórios salvos neste PC ficam aqui. Os sincronizados estão disponíveis na sua conta.', 'history.search': 'Buscar por URL…', 'history.filter': 'Filtrar por status', 'history.allStatuses': 'Todos os status', 'history.completed': 'Concluída', 'history.running': 'Em andamento', 'history.failed': 'Falhou', 'history.cancelled': 'Cancelada', 'history.empty': 'Nenhum relatório corresponde a estes filtros.',
  'scan.noPunches': 'Nenhuma análise ainda.', 'scan.startAddress': 'Comece digitando o endereço de um site.', 'scan.savedAccount': 'Salvo na sua conta', 'scan.savedLocal': 'Salvo neste PC',
  'watch.eyebrow': 'AUTOMAÇÃO', 'watch.title': 'Monitor de projetos', 'watch.subtitle': 'Escolha uma pasta de projeto e um endereço de site. O GorillaPunch verifica o site novamente quando você salva o código.', 'watch.createTitle': 'Monitorar um projeto', 'watch.createSubtitle': 'Escolha o endereço do site e a pasta do projeto para monitorar.', 'watch.address': 'Endereço do site', 'watch.auditType': 'Tipo de análise', 'watch.quickAudit': 'Análise rápida', 'watch.fullAudit': 'Análise completa', 'watch.chooseFolder': 'Escolher pasta', 'watch.monitoring': 'Monitorando', 'watch.paused': 'Pausado', 'watch.pause': 'Pausar monitoramento', 'watch.resume': 'Retomar monitoramento', 'watch.remove': 'Remover monitoramento', 'watch.lastStarted': 'última execução {date}', 'watch.emptyTitle': 'Nenhum projeto monitorado', 'watch.emptySubtitle': 'Adicione um projeto para verificar o site quando salvar o código.', 'watch.added': 'Monitor de projeto adicionado.',
  'settings.eyebrow': 'PREFERÊNCIAS', 'settings.title': 'Configurações', 'settings.subtitle': 'Escolha onde salvar relatórios e ajuste as análises.', 'settings.storageTitle': 'Armazenamento de relatórios', 'settings.storageSubtitle': 'Escolha onde salvar os novos relatórios.', 'settings.local': 'Armazenamento local', 'settings.localDesc': 'Relatórios e capturas de tela ficam neste PC. Não é necessário ter uma conta.', 'settings.ready': 'Pronto para usar', 'settings.cloud': 'Sincronização na nuvem', 'settings.cloudDesc': 'Entre para sincronizar os resultados das análises concluídas com sua conta. As capturas de tela ficam neste PC.', 'settings.unavailable': 'Indisponível no momento', 'settings.connected': 'Conta conectada', 'settings.signInBelow': 'Entre abaixo', 'settings.avatarInvalid': 'Escolha uma imagem PNG, JPEG ou WebP com menos de 8 MB.', 'settings.avatarProcessing': 'O processamento da imagem está indisponível.', 'settings.avatarCompression': 'Não foi possível compactar esta imagem. Escolha outra.',
  'settings.account': 'Conta GorillaPunch', 'settings.accountDesc': 'Entre ou crie uma conta para sincronizar relatórios.', 'settings.savingLocal': 'Salvando relatórios localmente', 'settings.pictureLabel': 'Escolher foto de perfil', 'settings.saving': 'Salvando…', 'settings.changePicture': 'Alterar foto', 'settings.remove': 'Remover', 'settings.pictureUpdated': 'Foto de perfil atualizada.', 'settings.pictureRemoved': 'Foto de perfil removida.', 'settings.pictureError': 'Não foi possível atualizar a foto de perfil.', 'settings.removePictureError': 'Não foi possível remover a foto.',
  'settings.syncing': 'Sincronizando…', 'settings.syncPending': 'Sincronizar {count} pendentes', 'settings.signOut': 'Sair', 'settings.signOutSuccess': 'Você saiu da conta.', 'settings.signOutError': 'Não foi possível sair. Tente novamente.', 'settings.createAccount': 'Criar conta', 'settings.signIn': 'Entrar', 'settings.accountSyncDesc': 'Use sua conta GorillaPunch para sincronizar relatórios.', 'settings.name': 'Nome', 'settings.email': 'E-mail', 'settings.password': 'Senha', 'settings.passwordLong': 'Senha (10 ou mais caracteres)', 'settings.acceptTerms': 'Aceite os Termos e a Política de Privacidade para criar uma conta.', 'settings.agreeTerms': 'Concordo com os', 'settings.terms': 'Termos', 'settings.and': 'e a', 'settings.privacy': 'Política de Privacidade', 'settings.wait': 'Aguarde…', 'settings.recovery': 'Para recuperar a conta, entre em contato com', 'settings.alreadyAccount': 'Já tem uma conta? Entre', 'settings.needAccount': 'Precisa de uma conta? Crie uma', 'settings.emailConfirm': 'Verifique seu e-mail e confirme a conta. Depois, entre aqui para sincronizar os relatórios.', 'settings.accountReady': 'Conta conectada. A sincronização na nuvem está pronta.', 'settings.connectError': 'Não foi possível conectar à conta. Tente novamente.', 'settings.cloudUnavailable': 'Sincronização na nuvem indisponível', 'settings.cloudUnavailableDesc': 'Tente novamente mais tarde ou fale com o suporte. Você ainda pode salvar relatórios neste PC.', 'settings.language': 'Idioma', 'settings.english': 'English', 'settings.portuguese': 'Português (Brasil)',
  'settings.auditTitle': 'Opções de análise', 'settings.auditSubtitle': 'Escolha quantas partes de cada site serão verificadas.', 'settings.defaultAudit': 'Análise padrão', 'settings.moreOptions': 'Mais opções', 'settings.pages': 'Páginas para verificar', 'settings.depth': 'Profundidade dos links', 'settings.timeLimit': 'Limite de tempo (segundos)', 'settings.concurrency': 'Análises simultâneas', 'settings.recommended': '1 — recomendado',
  'settings.preferencesTitle': 'Preferências do app', 'settings.preferencesSubtitle': 'Preferências de janela e notificações.', 'settings.theme': 'Tema', 'settings.system': 'sistema', 'settings.dark': 'escuro', 'settings.light': 'claro', 'settings.minimizeTray': 'Minimizar para a bandeja ao fechar', 'settings.notifications': 'Notificações de conclusão', 'settings.findDevSites': 'Encontrar sites de desenvolvimento automaticamente', 'settings.launchStartup': 'Iniciar com o Windows', 'settings.autoSync': 'Sincronizar automaticamente análises concluídas', 'settings.checkUpdates': 'Verificar atualizações', 'settings.checking': 'Verificando…', 'settings.updatesUnavailable': 'O serviço de atualização está indisponível no momento.', 'settings.updateCurrent': 'O GorillaPunch está atualizado.', 'settings.updateAvailable': 'A versão {version} está disponível.', 'settings.autoLanguage': 'Padrão do sistema',
  'report.back': 'Voltar', 'report.copyPrompt': 'Copiar instrução de correção', 'report.sync': 'Sincronizar', 'report.punchMode': 'ANÁLISE', 'report.export': 'Exportar', 'report.delete': 'Excluir relatório', 'report.launchGate': 'CRITÉRIO DE LANÇAMENTO', 'report.insufficient': 'COBERTURA INSUFICIENTE', 'report.noBlockers': 'Nenhum impedimento automatizado para o lançamento foi encontrado.', 'report.incomplete': 'Algumas verificações essenciais não foram concluídas. Revise as evidências antes de decidir.', 'report.resolve': 'Resolva primeiro as evidências mais graves antes do lançamento.', 'report.blockers': 'impedimentos', 'report.critical': 'críticos', 'report.high': 'altos', 'report.coverage': 'cobertura', 'report.savedAccount': 'Salvo na sua conta', 'report.savedLocal': 'Salvo neste PC', 'report.performance': 'Desempenho', 'report.security': 'Segurança', 'report.seo': 'SEO', 'report.accessibility': 'Acessibilidade', 'report.reliability': 'Confiabilidade', 'report.ux': 'Experiência do usuário', 'report.production': 'Produção', 'report.findings': 'Resultados', 'report.pages': 'Páginas', 'report.screenshots': 'Capturas de tela', 'report.metrics': 'Métricas', 'report.search': 'Buscar evidências…', 'report.searchLabel': 'Buscar evidências', 'report.filterSeverity': 'Filtrar por gravidade', 'report.allSeverities': 'Todas as gravidades', 'report.noneMatch': 'Nenhum resultado encontrado.', 'report.page': 'Página', 'report.status': 'Status', 'report.indexable': 'Indexável', 'report.loadTime': 'Tempo de carregamento', 'report.yes': 'Sim', 'report.no': 'Não', 'report.captureAlt': 'Área capturada {viewport}', 'report.imageUnavailable': 'Arquivo da captura indisponível', 'report.screenshotsLocal': 'As capturas de tela ficam apenas no computador que executou a análise.', 'report.metric': 'Métrica', 'report.value': 'Valor', 'report.why': 'Por que isso importa', 'report.evidence': 'Evidência', 'report.reproduce': 'Como reproduzir', 'report.recommendation': 'Recomendação', 'report.inspect': 'Inspecionar elemento ao vivo', 'report.closeDetails': 'Fechar detalhes do resultado', 'report.savedFile': 'Salvo em {path}', 'report.exportError': 'Falha ao exportar.', 'report.copiedPrompt': 'Instrução copiada com {count} resultados prioritários.', 'report.copiedPromptSingular': 'Instrução copiada com {count} resultado prioritário.', 'report.copiedSummary': 'Resumo do relatório copiado.', 'report.copyError': 'Não foi possível copiar a instrução de correção.', 'report.unavailable': 'Arquivo da captura indisponível', 'report.sevBlocker': 'Bloqueador', 'report.sevCritical': 'Crítico', 'report.sevHigh': 'Alto', 'report.sevMedium': 'Médio', 'report.sevLow': 'Baixo', 'report.sevOpportunity': 'Oportunidade', 'report.sevPassed': 'Aprovado',
  'arcade.eyebrow': 'ARCADE DO DESKTOP', 'arcade.title': 'Gorilla Shot', 'arcade.subtitle': 'Sobreviva à arena, reinicie seus sistemas e conclua os três setores.', 'arcade.loading': 'Carregando a arena', 'arcade.loadingDescription': 'Carregando os sistemas e renderizando o setor…', 'arcade.volume': 'Volume do jogo', 'arcade.gameLabel': 'Jogo Gorilla Shot', 'arcade.sectorSurvival': 'Sobrevivência por setor', 'arcade.savedLocal': 'Salvo localmente', 'arcade.offlinePending': 'Offline · sincronização pendente', 'arcade.cloudSynced': 'Progresso sincronizado na nuvem', 'arcade.cloudPending': 'Sincronização na nuvem pendente', 'arcade.mute': 'Silenciar áudio', 'arcade.unmute': 'Ativar áudio', 'arcade.pause': 'Pausar jogo', 'arcade.resume': 'Retomar jogo', 'arcade.fullscreen': 'Tela cheia', 'arcade.exitFullscreen': 'Sair da tela cheia', 'arcade.fullscreenError': 'Tela cheia indisponível nesta janela.', 'arcade.saveError': 'Não foi possível salvar o progresso do jogo.', 'arcade.startError': 'Não foi possível iniciar o jogo.', 'arcade.gameError': 'Não foi possível iniciar o jogo.', 'arcade.cloudError': 'Não foi possível sincronizar o progresso na nuvem.', 'arcade.statsLabel': 'Estatísticas da partida atual', 'arcade.sector': 'SETOR', 'arcade.health': 'VIDA', 'arcade.timeAlive': 'TEMPO VIVO', 'arcade.score': 'PONTUAÇÃO', 'arcade.enemies': 'INIMIGOS', 'arcade.systems': 'SISTEMAS', 'arcade.arena': 'Arena do Gorilla Shot', 'arcade.move': 'Mover', 'arcade.aim': 'Mirar', 'arcade.fire': 'Atirar', 'arcade.deploy': 'Escolher setor', 'arcade.progressLabel': 'Progresso do Gorilla Shot', 'arcade.progress': 'SEU PROGRESSO', 'arcade.record': 'Registro da missão', 'arcade.syncNow': 'Sincronizar agora', 'arcade.bestScore': 'MELHOR PONTUAÇÃO', 'arcade.longest': 'MAIOR SOBREVIVÊNCIA', 'arcade.totalTime': 'TEMPO TOTAL', 'arcade.runsClears': 'PARTIDAS / VITÓRIAS', 'arcade.recentRuns': 'Partidas recentes', 'arcade.runLabel': 'Setor {level}', 'arcade.points': 'pts', 'arcade.firstRecord': 'Conclua uma partida para começar seu registro da missão.', 'arcade.sectorOption': 'Setor {level}', 'arcade.cleared': 'CONCLUÍDO', 'arcade.failed': 'FALHOU', 'arcade.abandoned': 'ABANDONADO',
  'verdict.ready': 'PRONTO PARA LANÇAR', 'verdict.almost': 'QUASE PRONTO', 'verdict.notReady': 'NÃO ESTÁ PRONTO', 'verdict.doNotLaunch': 'NÃO LANCE', 'verdict.insufficient': 'COBERTURA INSUFICIENTE',
  'stage.resolving': 'Resolvendo o domínio', 'stage.opening': 'Abrindo o aplicativo', 'stage.headers': 'Lendo os cabeçalhos da resposta', 'stage.runtime': 'Inspecionando o navegador', 'stage.links': 'Percorrendo links internos', 'stage.damage': 'Calculando os problemas', 'stage.saving': 'Salvando o relatório da análise', 'stage.complete': 'Análise concluída', 'stage.cancelled': 'Análise cancelada', 'stage.interrupted': 'A análise foi interrompida', 'stage.closed': 'O app foi fechado antes da conclusão da análise', 'stage.queuePaused': 'Fila pausada', 'stage.waitingBrowser': 'Aguardando um navegador local', 'stage.warming': 'Preparando a análise',
  'settings.errValidEmail': 'Digite um endereço de e-mail válido.', 'settings.errPassword': 'Digite sua senha.', 'settings.errPasswordTooLong': 'Use uma senha com até 128 caracteres.', 'settings.errPasswordRange': 'Use uma senha com 10 a 128 caracteres.', 'settings.errCloudUnavailable': 'A sincronização na nuvem está indisponível. Tente novamente mais tarde ou fale com o suporte.', 'settings.errTooManyAttempts': 'Muitas tentativas. Aguarde um pouco e tente novamente.', 'settings.errReachAccount': 'Não foi possível acessar sua conta. Verifique a conexão e tente novamente.', 'settings.errBadCredentials': 'E-mail ou senha incorretos. Tente novamente.', 'settings.errCouldNotSignIn': 'Não foi possível entrar. Tente novamente.', 'settings.errAlreadyExists': 'Já existe uma conta com este e-mail. Entre na conta.', 'settings.errStrongerPassword': 'Escolha uma senha mais forte e tente novamente.', 'settings.errCouldNotCreate': 'Não foi possível criar sua conta. Tente novamente.', 'settings.errConnectAccount': 'Não foi possível conectar à conta. Tente novamente.',
  'misc.justNow': 'Agora mesmo', 'misc.complete': 'Concluído', 'misc.queued': 'Na fila', 'misc.cancelled': 'Cancelado', 'misc.failed': 'Falhou', 'misc.somethingWrong': 'Algo deu errado.',
};

export type DesktopMessage = MessageKey;
export type Translate = (key: DesktopMessage, values?: Record<string, string | number>) => string;

export function translate(locale: DesktopLocale, key: DesktopMessage, values?: Record<string, string | number>) {
  let result: string = locale === 'pt-BR' ? pt[key] : en[key];
  for (const [name, value] of Object.entries(values || {})) result = result.replaceAll(`{${name}}`, String(value));
  return result;
}

interface LocaleContextValue { locale: DesktopLocale; localePreference: DesktopLocalePreference; setLocalePreference(locale: DesktopLocalePreference): void; t: Translate }
const LocaleContext = createContext<LocaleContextValue | null>(null);

function systemLocale(): DesktopLocale {
  return navigator.language.toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
}

function initialLocalePreference(): DesktopLocalePreference {
  try {
    const saved = localStorage.getItem('gp-desktop-locale');
    if (saved === 'auto' || saved === 'en' || saved === 'pt-BR') return saved;
  } catch { /* Browser storage may be unavailable during startup. */ }
  return 'auto';
}

export function DesktopI18nProvider({ children }: { children: ReactNode }) {
  const [localePreference, setLocalePreference] = useState<DesktopLocalePreference>(initialLocalePreference);
  const locale = localePreference === 'auto' ? systemLocale() : localePreference;
  useEffect(() => {
    document.documentElement.lang = locale;
    try { localStorage.setItem('gp-desktop-locale', localePreference); } catch { /* The selection still applies for this session. */ }
  }, [locale, localePreference]);
  const t = useCallback<Translate>((key, values) => translate(locale, key, values), [locale]);
  const value = useMemo(() => ({ locale, localePreference, setLocalePreference, t }), [locale, localePreference, t]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useDesktopI18n() {
  const context = useContext(LocaleContext);
  if (!context) throw new Error('DesktopI18nProvider is missing.');
  return context;
}
