import { rule, type PunchCheck } from './types';
export const documentChecks: PunchCheck[] = [
  rule('accessibility.language', 'accessibility', 'Document language', ({ $ }) => ({ pass: !!$('html').attr('lang'), evidence: `html lang: ${$('html').attr('lang') || '(missing)'}`, recommendation: 'Set the correct BCP 47 language on the html element.', severity: 'MEDIUM' })),
  rule('accessibility.alt', 'accessibility', 'Image alternatives', ({ $ }) => { const missing = $('img:not([alt])'); return { pass: !missing.length, evidence: `${missing.length} images are missing alt attributes.\n${missing.slice(0, 15).map((_, n) => $(n).attr('src')).get().join('\n')}`, recommendation: 'Describe meaningful images with alt text. Decorative images should use an empty alt attribute.', severity: 'MEDIUM' }; }),
  rule('accessibility.form-labels', 'accessibility', 'Form field labels', ({ $ }) => { const missing = $('input:not([type="hidden"]):not([type="submit"]):not([type="button"]),textarea,select').filter((_, el) => { const input = $(el), id = input.attr('id'); return !input.attr('aria-label') && !input.attr('aria-labelledby') && !input.closest('label').length && !(id && $('label').filter((_, label) => $(label).attr('for') === id).length); }).length; return { pass: !missing, evidence: `${missing} form fields lack associated labels.`, recommendation: 'Associate labels with field IDs or use a meaningful accessible name.', severity: 'HIGH' }; }),
  rule('accessibility.landmarks', 'accessibility', 'Main content landmark', ({ $ }) => ({ pass: $('main,[role="main"]').length === 1, evidence: `${$('main,[role="main"]').length} main landmarks.`, recommendation: 'Mark the primary content with one main element.', severity: 'LOW' })),
  rule('accessibility.duplicate-ids', 'accessibility', 'Unique element IDs', ({ $ }) => { const ids = $('[id]').map((_, el) => $(el).attr('id')).get(); const duplicates = ids.filter((id, i) => ids.indexOf(id) !== i); return { pass: !duplicates.length, evidence: duplicates.join(', ') || 'No duplicate IDs found.', recommendation: 'Use unique IDs to keep labels, anchors and ARIA references unambiguous.', severity: 'MEDIUM' }; }),
  rule('ux.viewport', 'ux', 'Mobile viewport', ({ $ }) => ({ pass: /width=device-width/.test($('meta[name="viewport"]').attr('content') || ''), evidence: $('meta[name="viewport"]').attr('content') || 'Viewport metadata is missing.', recommendation: 'Use width=device-width, initial-scale=1. Do not disable user zoom.', severity: 'HIGH' })),
  rule('ux.zoom', 'ux', 'User zoom remains available', ({ $ }) => ({ pass: !/user-scalable=no|maximum-scale=1(?:,|$)/.test($('meta[name="viewport"]').attr('content') || ''), evidence: $('meta[name="viewport"]').attr('content') || 'No zoom restrictions declared.', recommendation: 'Allow users to zoom. Remove user-scalable=no and restrictive maximum-scale.', severity: 'MEDIUM' })),
  rule('ux.form-transport', 'ux', 'Secure form submission', ({ $, url }) => { const bad = $('form[action]').map((_, el) => $(el).attr('action') || '').get().filter(action => { try { return new URL(action, url).protocol !== 'https:'; } catch { return true; } }); return { pass: !bad.length, evidence: bad.join('\n') || 'No insecure form actions. No forms were submitted.', recommendation: 'Submit forms over HTTPS. Inspect actual server responses in an authorized journey test.', severity: 'HIGH' }; }),
  rule('production.placeholders', 'production', 'Visible placeholder content', ({ $ }) => { const clone = $.root().clone(); clone.find('script,style,pre,code').remove(); const matches = clone.text().match(/lorem ipsum|your app here|edit (?:app|src)\/page|welcome to nginx/gi) || []; return { pass: !matches.length, evidence: matches.slice(0, 10).join('\n') || 'No known placeholder phrases found.', recommendation: 'Replace placeholder copy before launch. Confirm these matches are not intentional documentation examples.', severity: 'LOW', confidence: 'medium' }; }),
  rule('production.local-urls', 'production', 'Production resource origins', ({ $ }) => { const bad = $('[src],form[action]').map((_, el) => $(el).attr('src') || $(el).attr('action') || '').get().filter(v => /https?:\/\/(localhost|127\.|0\.0\.0\.0|.*\.local[:/])/.test(v)); return { pass: !bad.length, evidence: bad.join('\n') || 'No local resource or form origins detected.', recommendation: 'Point production resources and APIs to publicly reachable production services.', severity: 'HIGH' }; }),
  rule('production.favicon', 'production', 'Browser icon', ({ $ }) => ({ pass: !!$('link[rel~="icon"]').attr('href'), evidence: $('link[rel~="icon"]').attr('href') || 'No favicon declared.', recommendation: 'Provide a browser icon so users can identify the application.', severity: 'OPPORTUNITY' })),
  rule('production.manifest', 'production', 'Application manifest', ({ $ }) => ({ pass: !!$('link[rel="manifest"]').attr('href'), evidence: $('link[rel="manifest"]').attr('href') || 'No application manifest declared. PWA support is optional.', recommendation: 'If this project is intended to be installable, provide and validate a web app manifest.', severity: 'OPPORTUNITY' })),
  rule('reliability.http', 'reliability', 'Page responds successfully', ({ response }) => ({ pass: response.status >= 200 && response.status < 400, evidence: `HTTP ${response.status}`, recommendation: 'Ensure the page returns a successful response. Inspect server logs using the request timestamp.', severity: response.status >= 500 ? 'BLOCKER' : 'HIGH' })),
  rule('performance.ttfb', 'performance', 'Initial document response', ({ response }) => ({ pass: response.duration < 1800, evidence: `Document fetch including body: ${response.duration} ms. This is a lab observation, not field TTFB.`, recommendation: 'Inspect server response time, redirects and document size. Repeat under representative conditions.', severity: 'MEDIUM', confidence: 'high' })),
  rule('performance.image-dimensions', 'performance', 'Reserved image dimensions', ({ $ }) => { const missing = $('img').filter((_, el) => !$(el).attr('width') || !$(el).attr('height')).length; return { pass: !missing, evidence: `${missing} images lack explicit width and height attributes. CSS aspect-ratio may provide an equivalent reservation.`, recommendation: 'Reserve image space with dimensions or aspect-ratio to reduce layout shifts.', severity: 'LOW', confidence: 'medium' }; }),
  rule('performance.compression', 'performance', 'Document compression', ({ response }) => ({ pass: !!response.headers['content-encoding'] || response.body.length < 2048, evidence: `Encoding: ${response.headers['content-encoding'] || 'none'}; decoded size ${response.body.length} bytes.`, recommendation: 'Enable Brotli or gzip for compressible HTML, CSS and JavaScript.', severity: 'LOW' })),
];
