import { rule, type PunchCheck } from './types';
export const securityChecks: PunchCheck[] = [
  rule('security.https', 'security', 'Encrypted transport', ({ url }) => ({ pass: url.startsWith('https:'), evidence: new URL(url).protocol, recommendation: 'Serve production over HTTPS with a valid certificate, and redirect HTTP to HTTPS.', severity: 'HIGH' })),
  ...[
    ['strict-transport-security', 'HSTS policy', 'MEDIUM'], ['content-security-policy', 'Content Security Policy', 'MEDIUM'],
    ['x-content-type-options', 'MIME sniffing protection', 'LOW'], ['referrer-policy', 'Referrer policy', 'LOW'], ['permissions-policy', 'Browser permissions policy', 'LOW'],
  ].map(([header, title, severity]) => rule(`security.${header}`, 'security', title, ({ response }) => ({ pass: !!response.headers[header], evidence: `${header}: ${response.headers[header] || '(missing)'}`, recommendation: `Set an appropriate ${header} response header at the application or reverse proxy.`, severity: severity as 'MEDIUM' | 'LOW' }))),
  rule('security.csp-quality', 'security', 'CSP script restrictions', ({ response }) => { const csp = response.headers['content-security-policy'] || ''; return { pass: !!csp && !/unsafe-eval|script-src[^;]*\*/.test(csp), evidence: csp || 'CSP is missing.', recommendation: 'Prefer nonces or hashes for scripts. Avoid unsafe-eval and wildcard script sources. Test a report-only policy before enforcement.', severity: 'MEDIUM' }; }),
  rule('security.framing', 'security', 'Frame restrictions', ({ response }) => { const value = response.headers['x-frame-options'] || response.headers['content-security-policy']?.match(/frame-ancestors[^;]*/)?.[0]; return { pass: !!value, evidence: value || 'No frame restrictions detected.', recommendation: 'Set CSP frame-ancestors to an explicit allowlist or none to reduce clickjacking risk.', severity: 'MEDIUM' }; }),
  rule('security.cookies', 'security', 'Cookie transport attributes', ({ response }) => { const cookies = (response.headers['set-cookie'] || '').split('\n').filter(Boolean); const missing = cookies.filter(c => !/;\s*secure(?:;|$)/i.test(c) || !/;\s*samesite=/i.test(c)).length; return { pass: missing === 0, evidence: `${cookies.length} Set-Cookie headers inspected; ${missing} lack Secure or SameSite. Values are never stored.`, recommendation: 'Use Secure and an appropriate SameSite policy. Use HttpOnly for session cookies; JavaScript-readable preference cookies may intentionally omit it.', severity: 'MEDIUM' }; }),
  rule('security.mixed-content', 'security', 'Secure page resources', ({ $, url }) => { const insecure = $('[src],link[href]').map((_, el) => $(el).attr('src') || $(el).attr('href') || '').get().filter(v => v.startsWith('http://')); return { pass: !url.startsWith('https:') || !insecure.length, evidence: insecure.slice(0, 20).join('\n') || 'No insecure resource references found.', recommendation: 'Serve scripts, styles, fonts and images over HTTPS.', severity: 'HIGH' }; }),
  rule('security.disclosure', 'security', 'Server version disclosure', ({ response }) => { const value = [response.headers.server, response.headers['x-powered-by']].filter(Boolean).join('; '); return { pass: !/\d+\.\d+|PHP|Express|ASP.NET/i.test(value), evidence: value || 'No server implementation disclosed.', recommendation: 'Remove unnecessary framework and detailed version headers.', severity: 'LOW' }; }),
  rule('security.cors', 'security', 'Cross-origin policy', ({ response }) => { const h = response.headers; return { pass: !(h['access-control-allow-origin'] === '*' && h['access-control-allow-credentials'] === 'true'), evidence: `Allow-Origin: ${h['access-control-allow-origin'] || '(absent)'}; Allow-Credentials: ${h['access-control-allow-credentials'] || '(absent)'}`, recommendation: 'For credentialed requests use explicit trusted origins. Wildcard plus credentials is invalid and browsers reject it.', severity: 'MEDIUM' }; }),
  rule('security.tls-expiry', 'security', 'Certificate lifetime', ({ response }) => { const days = response.tls ? Math.floor((Date.parse(response.tls.validTo) - Date.now()) / 86400000) : null; return { pass: days === null || days > 14, evidence: response.tls ? `Issuer: ${response.tls.issuer}; expires ${response.tls.validTo}; ${days} days remaining.` : 'Certificate details unavailable for this response. HTTPS requests still enforce platform certificate validation.', recommendation: 'Automate certificate renewal and alert before expiry.', severity: days !== null && days < 3 ? 'CRITICAL' : 'MEDIUM' }; }),
];
