import { rule, type PunchCheck } from './types';
export const seoChecks: PunchCheck[] = [
  rule('seo.title', 'seo', 'Descriptive document title', ({ $ }) => { const value = $('title').first().text().trim(); return { pass: value.length >= 10 && value.length <= 65, evidence: `Title (${value.length} characters): ${value || '(missing)'}`, recommendation: 'Use one descriptive title of roughly 10–65 characters. Describe this page, not just the product name.', severity: value ? 'LOW' : 'HIGH' }; }),
  rule('seo.description', 'seo', 'Search description', ({ $ }) => { const text = $('meta[name="description"]').attr('content') || ''; return { pass: text.length >= 50 && text.length <= 170, evidence: `Description (${text.length} characters): ${text || '(missing)'}`, recommendation: 'Add a useful page-specific meta description, generally 50–170 characters.', severity: 'LOW' }; }),
  rule('seo.canonical', 'seo', 'Canonical URL', ({ $, url }) => { const values = $('link[rel="canonical"]').map((_, n) => $(n).attr('href')).get(); let valid = false; try { const canonical = new URL(values[0], url); valid = values.length === 1 && canonical.origin === new URL(url).origin && ['http:', 'https:'].includes(canonical.protocol); } catch {} return { pass: valid, evidence: values.join('\n') || 'No canonical link found.', recommendation: 'Add a single absolute canonical URL matching the intended production origin.', severity: 'LOW' }; }),
  rule('seo.indexability', 'seo', 'Production page is indexable', ({ $, response }) => { const robots = $('meta[name="robots"],meta[name="googlebot"]').map((_, el) => $(el).attr('content')).get().join('; ') + '; ' + (response.headers['x-robots-tag'] || ''); return { pass: !/\b(noindex|none)\b/i.test(robots), evidence: robots.trim() === ';' ? 'No noindex directive detected in headers or metadata.' : robots, recommendation: 'Remove noindex if this public page should appear in search. Private dashboards may intentionally remain excluded; verify the page purpose.', severity: 'BLOCKER' }; }),
  rule('seo.h1', 'seo', 'Clear main heading', ({ $ }) => { const count = $('h1').length; return { pass: count === 1, evidence: `${count} H1 elements detected.`, recommendation: 'Use one clear main heading. Multiple H1s are a structural recommendation, not a launch blocker.', severity: 'LOW' }; }),
  rule('seo.headings', 'seo', 'Heading hierarchy', ({ $ }) => { let previous = 0; const skipped: string[] = []; $('h1,h2,h3,h4,h5,h6').each((_, el) => { const level = Number(el.tagName[1]); if (level > previous + 1) skipped.push(`${el.tagName}: ${$(el).text().slice(0, 120)}`); previous = level; }); return { pass: !skipped.length, evidence: skipped.join('\n') || 'Heading levels follow a logical sequence.', recommendation: 'Avoid skipping heading levels when structuring sections.', severity: 'LOW' }; }),
  ...['og:title', 'og:description', 'og:url', 'og:image'].map(property => rule(`seo.${property.replace(':', '-')}`, 'seo', `Social metadata ${property}`, ({ $ }) => { const value = $(`meta[property="${property}"]`).attr('content'); return { pass: !!value, evidence: value || `${property} is missing.`, recommendation: `Add ${property} for meaningful previews when a link is shared.`, severity: 'OPPORTUNITY' }; })),
  rule('seo.twitter', 'seo', 'Twitter Card metadata', ({ $ }) => ({ pass: !!$('meta[name="twitter:card"]').attr('content'), evidence: $('meta[name="twitter:card"]').attr('content') || 'No Twitter Card declared.', recommendation: 'Add twitter:card if rich social previews matter to this project.', severity: 'OPPORTUNITY' })),
  rule('seo.structured-data', 'seo', 'Structured data syntax', ({ $ }) => { const invalid: string[] = []; let count = 0; $('script[type="application/ld+json"]').each((_, el) => { count++; try { JSON.parse($(el).text()); } catch { invalid.push(`JSON-LD block ${count} contains invalid JSON.`); } }); return { pass: !invalid.length, evidence: invalid.join('\n') || `${count} JSON-LD blocks inspected.`, recommendation: 'Validate JSON-LD syntax, then verify vocabulary and required fields with the relevant schema validator.', severity: 'LOW' }; }),
  rule('seo.link-labels', 'seo', 'Useful link names', ({ $ }) => { const missing = $('a[href]').filter((_, el) => !$(el).text().trim() && !$(el).attr('aria-label') && !$(el).find('img[alt]').attr('alt')).length; return { pass: !missing, evidence: `${missing} links without visible or accessible text.`, recommendation: 'Give each link a meaningful accessible name.', severity: 'MEDIUM' }; }),
];
